// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })(['./Regex'], function(RegexValidatorRule) {
    var EmailValidatorRule;
    return EmailValidatorRule = (function(_super) {
      __extends(EmailValidatorRule, _super);

      function EmailValidatorRule(options) {
        if (options == null) {
          options = {};
        }
        if (options != null) {
          if (options.regex == null) {
            options.regex = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
          }
        }
        EmailValidatorRule.__super__.constructor.call(this, options);
      }

      EmailValidatorRule.prototype.getViolationCodes = function() {
        return ['NotAnEmail'];
      };

      return EmailValidatorRule;

    })(RegexValidatorRule);
  });

}).call(this);
