// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })(['./Rule'], function(ValidatorRule) {
    var MaxLengthValidatorRule;
    return MaxLengthValidatorRule = (function(_super) {
      __extends(MaxLengthValidatorRule, _super);

      function MaxLengthValidatorRule(options) {
        this.options = {
          maxLength: 100
        };
        MaxLengthValidatorRule.__super__.constructor.apply(this, arguments);
      }

      MaxLengthValidatorRule.prototype.getViolationCodes = function() {
        return ['TooLong'];
      };

      MaxLengthValidatorRule.prototype.validate = function(str) {
        if (str == null) {
          return [];
        }
        if (str.length > this.options.maxLength) {
          return ['TooLong'];
        }
        return [];
      };

      return MaxLengthValidatorRule;

    })(ValidatorRule);
  });

}).call(this);
