// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })(['./Rule'], function(ValidatorRule) {
    var ObjectValidatorRule;
    return ObjectValidatorRule = (function(_super) {
      var union;

      __extends(ObjectValidatorRule, _super);

      union = function() {
        var arr, arrays, el, result, _i, _j, _len, _len1;
        arrays = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        result = [];
        for (_i = 0, _len = arrays.length; _i < _len; _i++) {
          arr = arrays[_i];
          if ((arr != null) && arr.length > 0) {
            for (_j = 0, _len1 = arr.length; _j < _len1; _j++) {
              el = arr[_j];
              if (!(__indexOf.call(result, el) >= 0)) {
                result.push(el);
              }
            }
          }
        }
        return result;
      };

      ObjectValidatorRule.prototype.setOptions = function(options) {
        var key, rule, _ref;
        _ref = this.rules;
        for (key in _ref) {
          rule = _ref[key];
          rule.setOptions(options);
        }
        return ObjectValidatorRule.__super__.setOptions.apply(this, arguments);
      };

      function ObjectValidatorRule(rules, options) {
        this.rules = rules;
        ObjectValidatorRule.__super__.constructor.call(this, options);
      }

      ObjectValidatorRule.prototype.getViolationCodes = function() {
        var key, rule;
        return union.apply(null, (function() {
          var _ref, _results;
          _ref = this.rules;
          _results = [];
          for (key in _ref) {
            rule = _ref[key];
            _results.push(rule.getViolationCodes());
          }
          return _results;
        }).call(this));
      };

      ObjectValidatorRule.prototype.validate = function(obj) {
        var key, rule;
        if (obj == null) {
          return [];
        }
        return union.apply(null, (function() {
          var _ref, _results;
          _ref = this.rules;
          _results = [];
          for (key in _ref) {
            rule = _ref[key];
            _results.push(rule.validate(obj[key]));
          }
          return _results;
        }).call(this));
      };

      return ObjectValidatorRule;

    })(ValidatorRule);
  });

}).call(this);
