// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })(['./Rule'], function(ValidatorRule) {
    var RegexValidatorRule;
    return RegexValidatorRule = (function(_super) {
      __extends(RegexValidatorRule, _super);

      function RegexValidatorRule(options) {
        this.options = {
          regex: /(?:)/
        };
        RegexValidatorRule.__super__.constructor.call(this, options);
      }

      RegexValidatorRule.prototype.getViolationCodes = function() {
        return ['RegexMismatch'];
      };

      RegexValidatorRule.prototype.validate = function(str) {
        if (str == null) {
          return [];
        }
        if (!this.options.regex.test(str)) {
          return this.getViolationCodes();
        }
        return [];
      };

      return RegexValidatorRule;

    })(ValidatorRule);
  });

}).call(this);
