// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty;

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })([], function() {
    var ValidatorRule;
    return ValidatorRule = (function() {
      function ValidatorRule(options) {
        if (this.options == null) {
          this.options = {};
        }
        this.setOptions(options);
      }

      ValidatorRule.prototype.setOptions = function(options) {
        var option, value, _results;
        if (options != null) {
          _results = [];
          for (option in options) {
            if (!__hasProp.call(options, option)) continue;
            value = options[option];
            _results.push(this.options[option] = value);
          }
          return _results;
        }
      };

      ValidatorRule.prototype.getViolationCodes = function() {
        return [];
      };

      ValidatorRule.prototype.validate = function(value) {
        return [];
      };

      ValidatorRule.prototype.isValid = function(value) {
        return this.validate(value).length === 0;
      };

      return ValidatorRule;

    })();
  });

}).call(this);
