// Generated by CoffeeScript 1.7.1
(function() {
  var ruleNames, rulePaths,
    __slice = [].slice;

  ruleNames = ['And', 'Blacklist', 'Email', 'Existence', 'MaxLength', 'MinLength', 'Not', 'Or', 'Regex', 'Rule', 'Object', 'ViolationCodeModifier'];

  rulePaths = ruleNames.map(function(s) {
    return './rules/' + s;
  });

  (function(modules, factory) {
    var m;
    if (typeof define === 'function' && define.amd) {
      return define(modules, factory);
    } else {
      return module.exports = factory.apply(null, (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = modules.length; _i < _len; _i++) {
          m = modules[_i];
          _results.push(require(m));
        }
        return _results;
      })());
    }
  })(rulePaths, function() {
    var i, result, rules, _i, _ref;
    rules = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = {};
    for (i = _i = 0, _ref = ruleNames.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      result[ruleNames[i]] = rules[i];
    }
    return result;
  });

}).call(this);
