// Generated by CoffeeScript 1.9.0
(function() {
  define(['lib/ValidatorRules'], function(Rules) {
    return new Rules.ViolationCodeModifier(new Rules.And([new Rules.Existence(), new Rules.Blacklist(), new Rules.Email(), new Rules.MaxLength()]), 'Email');
  });

}).call(this);
