// Generated by CoffeeScript 1.9.0
(function() {
  define(['lib/ValidatorRules'], function(Rules) {
    return new Rules.ViolationCodeModifier(new Rules.MaxLength(), 'FirstName');
  });

}).call(this);
